### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by ntnhon**
- Use guard to avoid pyramid of doom
- Refactor coding style (add space between variable name and type, spacing between functions...).
- Use static computed properties for configs.
- Update example.

### CODE REVIEW

**Comment by ntnhon** [comment]
Hi @Liquicit 
Have a look at this PR :)

**Comment by Liquicit** [comment]
Thanks for all the help! Your code is much cleaner than mine, I didn't know how to properly use get ters & setters either. I appreciate all your help, Cheers!

**Comment by ntnhon** [comment]
My pleasure. I forgot to update the readme.

**Comment by ntnhon** [comment]
Ah you did change it. You rock 👍

**Pull request merged**
